[language]
name = "go"
extensions = [".go"]

[detection]
package_files = [
    "go.mod",
    "go.sum",
    "glide.yaml",
    "glide.lock",
    "Gopkg.toml",
    "Gopkg.lock",
]

[[package_managers]]
files = ["go.mod"]
manager = "go"
priority = 10

[[package_managers]]
files = ["Gopkg.toml", "Gopkg.lock"]
manager = "dep"
priority = 8

[[package_managers]]
files = ["glide.yaml", "glide.lock"]
manager = "glide"
priority = 7
